require:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3.1
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'config.ru'

Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 120
