require:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3.1
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'config.ru'
    - 'db/schema.rb'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 120
Style/HashSyntax:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
